= PlantUML diagrams styling

== Overview

.PlantUML Diagrams
[plantuml]
....
@startmindmap
include::partial$plantuml-wbsmm-style.iuml[]
* PlantUML
 * UML diagrams
  * Behaviour diagrams
   * Use cases
   * Activities
   * States
   * Interactions
    * Sequences
    * Communication
  * Structure diagrams
   * Classes
   * Objects
   * Packages
   * Components
   * Deployment
 * Other diagrams
  * Mindmaps
  * Work Breakdown Structures (WBS)
  * C4 diagrams
@endmindmap
....

The next pages show examples of diagrams with their available elements, to verify the styling.
Two pointers for more information on the syntax and the meaning of diagrams:

- The https://plantuml.com[PlantUML website^] shows how to specify and adapt elements of diagrams in more detail.
- https://www.uml-diagrams.org/[Find out more about UML diagrams^]

== Color conventions

We include a PlantUML configuration file when generating diagram images.
This configuration file uses color variables across UML elements, divided in types of diagram elements.

.Color conventions for types of diagram elements
[plantuml]
....
@startuml
skinparam participant<<node_1>> {
  $node_1_style(1)
}
skinparam participant<<node_2>> {
  $node_2_style(1)
}
skinparam participant<<logic>> {
  $logic_style(1)
}
skinparam participant<<group>> {
  $group_style(1)
}
skinparam participant<<divider>> {
  $divider_style(1)
}
skinparam participant<<note>> {
  $note_1_style(1)
}

hide footbox

participant "Primary node" <<node 1>>
participant "Secondary node" <<node 2>>
participant "Logic element" <<logic>>
participant "Grouping element" <<group>>
participant "Divider element" <<divider>>
participant "Note" <<note>>

"Primary node" -> "Note" : messages and flows
@enduml
....

The admonition colors are also included, to make it easy to use them in diagrams as well.

.Using admonition colors for elements
[plantuml]
....
@startuml
hide footbox

participant tip <<(T,$tip_color)>>
note over tip $tip_color: Tip

participant note <<(N,$note_color)>>
/ note over note $note_color: Note

participant warning <<(W,$warning_color)>>
/ note over warning $warning_color: Warning

participant caution <<(C,$caution_color)>>
/ note over caution $caution_color: Caution

participant important <<(I,$important_color)>>
/ note over important $important_color: Important
@enduml
....

.Source for the example above
[source, plantuml]
....
@startuml
hide footbox

participant tip <<(T,$tip_color)>>
note over tip $tip_color: Tip

participant note <<(N,$note_color)>>
/ note over note $note_color: Note

participant warning <<(W,$warning_color)>>
/ note over warning $warning_color: Warning

participant caution <<(C,$caution_color)>>
/ note over caution $caution_color: Caution

participant important <<(I,$important_color)>>
/ note over important $important_color: Important
@enduml
....


== Add the PlantUML configuration

The Kroki server that generates PlantUML diagrams has an option to include the PlantUML configuration file.
 
.In Antora playbook, add a reference to the PlantUML configuration
[source, yaml]
....
asciidoc:
  extensions:
  - asciidoctor-kroki
  attributes:
    ... # <1>
    kroki-server-url: http://localhost:18181
    kroki-plantuml-include: plantuml-styling.cfg # <2>
....
<1> Other configuration options
<2> Location of the PlantUML styling
