= PlantUML diagrams

== Overview

.PlantUML Diagrams
[plantuml]
----
@startmindmap
include::lib-style::partial$plantuml-wbsmm-style.iuml[]
<style>
mindmapDiagram {
  node {
    MaximumWidth 400
  }
}
</style>
* PlantUML diagrams
 * UML (Unified Modeling Language)
 * C4 models
 * Mindmaps
 * WBS (Work Breakdown Structures)
 * SDL (Specification and Description Language)
@endmindmap
----

The next pages show examples of diagrams with their available elements, to verify the styling.
Two pointers for more information on the syntax and the meaning of diagrams:

- The https://plantuml.com[PlantUML website^] shows how to specify and adapt elements of diagrams in more detail.
- https://www.uml-diagrams.org/[Find out more about UML diagrams^]

== Colour conventions

We include a PlantUML configuration file when generating diagram images.
This configuration file uses color variables across UML elements, divided in types of diagram elements.

.Colour conventions for types of diagram elements
[plantuml]
----
include::example$puml/colour_conventions.puml[]
----

The boxes above are coloured using stereotypes.

.Source for the example above
[source, plantuml]
----
include::example$puml/colour_conventions.puml[]
----

The admonition colors are also included, to make it easy to use them in diagrams as well.

.Using admonition colors for elements
[plantuml]
----
include::example$puml/admonition_colours.puml[]
----

.Source for the example above
[source, plantuml]
----
include::example$puml/admonition_colours.puml[]
----


== Add the PlantUML configuration

The Kroki server that generates PlantUML diagrams has an option to include the PlantUML configuration file.
 
.In Antora playbook, add a reference to the PlantUML configuration
[source, yaml]
....
asciidoc:
  extensions:
  - asciidoctor-kroki
  attributes:
    ... # <1>
    kroki-server-url: http://localhost:18181
    kroki-plantuml-include: plantuml-styling.cfg # <2>
....
<1> Other configuration options
<2> Location of the PlantUML styling
