@startuml
!include <C4/C4_Component>

LAYOUT_WITH_LEGEND()

Container_Boundary(boundary1, "Container_Boundary", "Boundary type") {
  Component(component1, "Component", "Technology", "Optional Description")
  ComponentQueue(cqueue, "ComponentQueue", "Technology")
  ComponentDb(cdb, "ComponentDb", "Technology", "Optional Description")

  Rel_R(component1, cdb, "Rel_R", "Optional Technology")
  BiRel_L(component1, cqueue, "BiRel", "Optional")
}

Container_Boundary(boundary2, "Boundary", "Boundary type") {
  Component_Ext(component2, "Component_Ext", "Technology", "Optional Description")
  ComponentQueue_Ext(cqueue2, "ComponentQueue_Ext", "Technology")
  ComponentDb_Ext(cdb2, "ComponentDb_Ext", "Technology", "Optional Description")

  Rel_R(component2, cdb2, "Rel_R", "Optional Technology")
  BiRel_L(component2, cqueue2, "BiRel", "Optional")
}

Rel(component1, component2, "Rel")
@enduml
