@startuml
  actor "Actor" <<Stereotype>>
  note right of :Actor:: Note

  package "Package" <<Stereotype>> {
    usecase UseCase as "Use case" <<Stereotype>>
  }
 
  useCase UseCase2 as "Additional use case"
  
  :Actor: --> UseCase
  UseCase <|-- UseCase2
@enduml
