@startuml
|Swimlane 1|
start

  if (condition) then (one)
  partition "Partition" {
    if (first?) then (yes)
      :Action A;
    elseif (second?) then (yes)
      :Action B;
    else (no)
      :Action C;
    endif
  }
  
  repeat
    :Repeat;
    note right: Note
  repeat while (Again?) is (yes) not (no)

  fork
    :Parallel X;
  fork again
    :Parallel Y;
  end merge
  
  switch (Switch)
  case (Case i)
    :Action i;
  case (Case ii)
    :Action ii;
  case (Case iii)
    :Action iii;
  endswitch

else (two)
  -[dotted]->

  |Swimlane 2|
  :Input<
  :Output>
  floating note right
    Floating note
    ----
    Second line
  end note
  
  :Block|
  :Rectangle]
  :Parallel 1/
  :Parallel 2\\
  :Brackets}

  split
    :Kill;
    kill
  split again
    :End;
    end;
  split again
    :Detach;
    (Z)
    detach
  end split
endif

|Swimlane 1|  

stop
@enduml
