@startuml
!include <C4/C4_Container>

LAYOUT_WITH_LEGEND()

System_Boundary(boundary1, "System_Boundary", "Boundary type") {
  Container(container1, "Container", "Technology", "Optional Description")
  ContainerQueue(cqueue, "ContainerQueue", "Technology")
  ContainerDb(cdb, "ContainerDb", "Technology", "Optional Description")

  Rel_R(container1, cdb, "Rel_R", "Optional Technology")
  BiRel_L(container1, cqueue, "BiRel", "Optional")
}

System_Boundary(boundary2, "System_Boundary", "Boundary type") {
  Container_Ext(container2, "Container_Ext", "Technology", "Optional Description")
  ContainerQueue_Ext(cqueue2, "ContainerQueue_Ext", "Technology")
  ContainerDb_Ext(cdb2, "ContainerDb_Ext", "Technology", "Optional Description")

  Rel_R(container2, cdb2, "Rel_R", "Optional Technology")
  BiRel_L(container2, cqueue2, "BiRel", "Optional")
}

Rel(container1, container2, "Rel")
@enduml
