@startuml
!include <C4/C4_Context>
!include <tupadr3/font-awesome/users>

LAYOUT_WITH_LEGEND()

Person(person1, "Person", "Optional Description")
Person(group1, "Group", "Optional Description", $sprite="users")

Boundary(boundary1, "Boundary", "Boundary type") {
  System(system1, "System", "Optional Description")
  SystemQueue(squeue, "SystemQueue", "Optional Description")
  SystemDb(sdb, "SystemDb", "Optional Description")

  Rel_R(system1, sdb, "Rel_R", "Optional Technology")
  BiRel_L(system1, squeue, "BiRel_L", "Optional")
}

Rel(person1, system1, "Rel", "Optional Technology")

Boundary(boundary2, "Boundary", "Boundary type") {
  System_Ext(system2, "System_Ext", "Optional Description")
  SystemQueue_Ext(squeue2, "SystemQueue_Ext", "Optional Description")
  SystemDb_Ext(sdb2, "SystemDb_Ext", "Optional Description")

  Rel_R(system2, sdb2, "Rel_R", "Optional Technology")
  BiRel_L(system2, squeue2, "BiRel_L", "Optional")
}

Rel(system1, system2, "Rel")

@enduml
